### PR TITLE
Fixes issue #7: seeking in simple-streamcb does not work

### PR DESCRIPTION
**Pull request by wphilips**
Simple change which makes it possible to seek in the stream using arrow keys.

### CODE REVIEW

**Comment by wm4** [comment]
Can you implement the size check with a seek to the end of the file (and then back)? That's the more normal way to determine the size. The st_size field can apparently lie sometimes.

**Comment by wphilips** [comment]
Can you explain why st_size would be incorrect?

Actually, the following website suggests that what you propose may be incorrect:
https://www.securecoding.cert.org/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file

**Comment by wm4** [comment]
I don't quite agree with that site. They confusingly explain some possible confusion if text mode is used (yeah, never use text mode, although it's a no-op on POSIX). Then they present a sample program which they claim buggy, although it doesn't use text mode at all. The next sample (which they claim compliant) then uses ftello instead of ftell - again this has nothing to do with text mode.

They do explain that ftello is preferable because off_t has a higher range. (Hilariously they don't explain that many implementations require you to set obscure macros to make off_t actually 64 bit.) And of course that's true, and there's nothing about why the fseek+ftell approach is supposed to be bad.

Anyway, files for which st_size reports 0, even though there are more than 0 bytes readable, do exists. fstat probably also succeeds on pipes, for which st_size will be 0 AFAIK? So it just seems more robust to seek to the end (of course with error checks). Of course you need to seek back to the original position too.

You don't need to change this. It's only a suggestion. We don't need to necessarily use good practices in our sample code for things that are not directly related to libmpv. But it would still  be preferable and nice.

**Comment by wphilips** [comment]
Yes, I see. I fail to see the use of non-binary files anyway. Seems like an artefact from msdos days.

Note that the example will not properly work on fifo's anyway, and ftell will not change that
as seeking on pipes makes no sense.
 
An interesting case would be seeking on growing files.

In any case, the simpler the example the better. It does not have to handle
all possible inputs.

Out of curiosity only: apart from files currently being modified/written, and pipes, sockets, ...
where filesize has no meaning, are there really any cases where st_size would be incorrect?
For files being written, st_size could be somewhat out of date due to stale metadata, but there is no way
to avoid that even with ftell and such.

**Comment by wm4** [comment]
> I fail to see the use of non-binary files anyway. Seems like an artefact from msdos days.

Indeed.

> Out of curiosity only: apart from files currently being modified/written, and pipes, sockets, ...
where filesize has no meaning, are there really any cases where st_size would be incorrect?

I don't think so. There is the `/proc` strangeness, where files are regular files, but not seekable, and st_size reports 0. (At least when running `stat`, haven't tried `fstat`.) So probing via seek/tell seems most robust to probe the file size.

**Comment by wm4** [comment]
Oh wait.

**Pull request merged**
